.global asm_func1
asm_func1:
    # write below this line 
    #######################
    srai a7, a7, 13
    li a0, 0x1
    and a0, a0, a7
    xori a0, a0, 1

    #######################
    # write above this line 
    ret     # do not remove!

.global asm_func2
asm_func2:
    # write below this line 
    #######################
    # a0 32-bit value
    


    #######################
    # write above this line 
    ret     # do not remove!

.global asm_func3
asm_func3:
    # write below this line 
    #######################

    

    #######################
    # write above this line 
    ret     # do not remove!